proof.pdf: proof.tex proof.bib
	-pdflatex proof
	-pdflatex proof
	-pdflatex proof
	-bibtex proof
	-pdflatex proof
	-pdflatex proof
	-pdflatex proof
clean:
	-rm *.aux
	-rm *.bbl
	-rm *.blg
	-rm *.log
	-rm *.pdf
	-rm *~
	-rm *.out
