#!/bin/bash
for a in IP CRC FFT
do
    for n in MiniWellScoped TemplateHaskell
    do
	for i in {1..10}
	do
	    ./clean
	    rm ${a}${n}
	    /usr/bin/time -f "%e" -a -o time${a}${n}Compile ghc -o ${a}${n} Examples/Feldspar/${a}/${n}.hs -Wall -fno-warn-orphans -XNoMonomorphismRestriction -XPolyKinds -XDataKinds -XConstraintKinds -XTypeOperators -XTypeFamilies -XGADTs -XFlexibleInstances -XFlexibleContexts -XStandaloneDeriving -XDeriveFoldable -XDeriveFunctor -XDeriveTraversable -XDeriveDataTypeable -XDeriveGeneric -XNoUndecidableInstances -XMonoLocalBinds -XScopedTypeVariables -XMultiParamTypeClasses -XImplicitParams -XTemplateHaskell -XRankNTypes -XPatternSynonyms -XViewPatterns -XNoImplicitPrelude
	done
    done
done
./clean
for f in NoNrm # Nrm NoNrm
do
    for a in IP CRC FFT
    do
	for n in MiniWellScoped TemplateHaskell
	do
	    for i in {1..10}
	    do
		rm ${f}${a}${n}.c
		/usr/bin/time -f "%e" -a -o time${f}${a}${n}Gen ./${a}${n} ${f}
	    done
	done
    done
done
./clean
for f in NoNrm # Nrm NoNrm
do
    for a in IP CRC FFT
    do
	for n in MiniWellScoped TemplateHaskell
	do
	    for i in {1..10}
	    do
		rm ${f}${a}${n}
		/usr/bin/time -f "%e" -a -o time${f}${a}${n}GCC gcc -o ${f}${a}${n} ${f}${a}${n}.c -lm -std=c99
	    done
	done
    done
done
for f in NoNrm # Nrm NoNrm
do
    for a in IP CRC FFT
    do
	for n in MiniWellScoped TemplateHaskell
	do
	    for i in {1..10}
	    do
		if [ ${a}${n} != FFTMiniWellScoped ]; then
		    rm ImageFFT.pgm
		    rm Image.pbm
		    /usr/bin/time -f "%e" -a -o time${f}${a}${n}Run ./${f}${a}${n}
                fi
	    done
	done
    done
done
for f in NoNrm # Nrm NoNrm
do
    for a in IP CRC FFT
    do
	for n in MiniWellScoped TemplateHaskell
	do
	    rm ${a}${n}
	    rm ${f}${a}${n}.c
	    rm ${f}${a}${n}
	done
    done
done
rm ImageFFT.pgm
rm Image.pbm
./clean
F=Experiment_$(date +%Y-%m-%d-%H-%M-%S)
mkdir $F
for file in time*; do
    mv $file ./$F/$file
done
./Process ./$F/
